Traceback (most recent call last):
  File "establecimientoConeccion.py", line 26, in <module>
    data = sock.recv(1)
  File "<string>", line 5, in recv
bluetooth.btcommon.BluetoothError: (103, 'Software caused connection abort')
